openapi: 3.0.1
servers:
  - url: https://api-ip.fssprus.ru/api/v1.0/
paths:
  /search/physical?region={region}:
    get:
      
      parameters:
      
      - name: region
        in: path

        required: true
        schema:
          type: string
           
      - name: firstname
        in: path
      
      responses:
          default:
            statusCode: 200
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
          schema:
            type: array
            items:
              $ref: '#/definitions/Response'
          
components:
  securitySchemes:

    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: query       # can be "header", "query" or "cookie"
      name: token  # name of the header, query parameter or cookie

 
definitions:
  Response:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Category
security:
  - ApiKeyAuth: []  
